# Generated by Django 5.2.5 on 2025-09-02 09:13

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=50)),
                ('blog_img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('blog_text', models.TextField()),
                ('blog_upload', models.DateTimeField(default=datetime.datetime(2025, 9, 2, 9, 13, 43, 349646, tzinfo=datetime.timezone.utc))),
                ('blog_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Bad'), (2, 'Normal'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], max_length=1)),
                ('comment', models.CharField(blank=True)),
                ('reviewer_name', models.CharField()),
                ('r_date', models.DateTimeField(auto_now_add=True)),
                ('r_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blogpost.blogs')),
            ],
        ),
    ]
